name: custom_radio_grouped_button
description: Custom Radio Buttons and Grouped Check Box Button
version: 1.0.8

homepage: https://github.com/ketanchoyal/custom_radio_grouped_button

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
